<?php
/**
 * Generates body.theme-green explicit overrides from moodle.css.
 * Run: C:\xampp82\php\php.exe local/support/generate_green_css.php
 * Output goes to local/support/styles/theme-green-generated.css
 */

$moodlecss = __DIR__ . '/../../theme/boost/style/moodle.css';
$outfile    = __DIR__ . '/styles/theme-green.css';

$css = file_get_contents($moodlecss);
// No var() substitution needed — moodle.css should have raw hex values.

// Find all rule blocks that contain #e63612 or #ca3120.
// Regex: capture selector(s) and declaration block.
preg_match_all(
    '/([^{};@][^{}]*)\{([^{}]*(?:#e63612|#ca3120)[^{}]*)\}/i',
    $css,
    $matches,
    PREG_SET_ORDER
);

$rules = [];
foreach ($matches as $m) {
    $selector = trim($m[1]);
    $decls    = trim($m[2]);

    // Skip :root / [data-bs-theme] variable definitions.
    if (preg_match('/^:root|\[data-bs-theme/i', $selector)) {
        continue;
    }
    // Skip keyframes/from/to
    if (preg_match('/^(from|to|\d)/', $selector)) {
        continue;
    }

    // Keep ONLY declarations that contained the brand colour — ignore the rest.
    $decl_lines = [];
    foreach (explode(';', $decls) as $decl) {
        $decl = trim($decl);
        if ($decl === '') {
            continue;
        }
        if (stripos($decl, '#e63612') === false && stripos($decl, '#ca3120') === false) {
            continue; // Not a brand-colour declaration — skip.
        }
        $decl = str_replace('#e63612', '#4f773c', $decl);
        $decl = str_replace('#ca3120', '#4f773c', $decl);
        $decl_lines[] = $decl;
    }
    if (empty($decl_lines)) {
        continue;
    }

    // Scope every sub-selector under body.theme-green.
    $parts  = explode(',', $selector);
    $scoped = [];
    foreach ($parts as $part) {
        $part = trim($part);
        if ($part === '') {
            continue;
        }
        $scoped[] = 'body.theme-green ' . $part;
    }
    if (empty($scoped)) {
        continue;
    }

    $rules[] = implode(",\n", $scoped) . " {\n    "
        . implode(";\n    ", $decl_lines) . ";\n}";
}

// Build output file.
$header = <<<CSS
/**
 * theme-green.css — explicit colour overrides for body.theme-green.
 * Auto-generated by generate_green_css.php from moodle.css.
 * DO NOT EDIT MANUALLY — re-run the generator after moodle.css changes.
 *
 * Green brand colour: #4f773c  (replaces #e63612 primary, #ca3120 danger)
 */

/* ── Core CSS custom properties ────────────────────────────────────────── */

body.theme-green {
    --brand-color:             #4f773c;
    --brand-color-dark:        #3f5f30;
    --platform-color:          #4f773c;
    --bs-primary:              #4f773c;
    --bs-primary-rgb:          79, 119, 60;
    --bs-blue:                 #4f773c;
    --bs-danger:               #4f773c;
    --bs-danger-rgb:           79, 119, 60;
    --bs-red:                  #4f773c;
    --bs-link-color:           #4f773c;
    --bs-link-color-rgb:       79, 119, 60;
    --bs-link-hover-color:     #3f5f30;
    --bs-link-hover-color-rgb: 63, 95, 48;
    --bs-form-invalid-color:        #4f773c;
    --bs-form-invalid-border-color: #4f773c;
}

/* ── btn-primary hover/active shades (blue in moodle.css, override to green) */

body.theme-green .btn-primary {
    --bs-btn-hover-bg:            #3f5f30;
    --bs-btn-hover-border-color:  #3a5a2c;
    --bs-btn-active-bg:           #365528;
    --bs-btn-active-border-color: #315023;
    --bs-btn-focus-shadow-rgb:    79, 119, 60;
}

body.theme-green .btn-outline-primary {
    --bs-btn-focus-shadow-rgb: 79, 119, 60;
}

/* ── userinitials background ────────────────────────────────────────────── */

body.theme-green .userinitials {
    background: #f0f5ee;
}

/* ── icons-collapse-expand button ───────────────────────────────────────── */

body.theme-green .btn-icon.icons-collapse-expand {
    color: #4f773c;
    background-color: #f0f5ee;
}

/* ── Explicit per-selector overrides (all #e63612 / #ca3120 usages) ──────── */

CSS;

$output = $header . implode("\n\n", $rules) . "\n";
file_put_contents($outfile, $output);

echo "Generated " . count($rules) . " rules -> $outfile\n";
